### ISSUE TITLE
skip some numbers for sequential_id [feature]

### ISSUE THREAD

**Issue by twnaing** [derrickreimer/sequenced#31]
My case is we have some number already taken by the user. So when sequenced generates a sequential_id, the numbers have to be skipped. I have basic logic but not successful in implementing in gem (a noob).

```ruby
module Sequenced
  class Generator
    attr_reader :record, :scope, :column, :start_at, :skip, :forget

    def initialize(record, options = {})
      @record = record
      @scope = options[:scope]
      @column = options[:column].to_sym
      @start_at = options[:start_at]
      @skip = options[:skip]
      @forget = options[:forget]
    end
...
    def next_id      
      next_id_in_sequence.tap do |id|
        id += 1 until ( ! self.forget.map{ |d| d === id }.any? && unique?(id) )
      end
    end
```
forget option accepts flat array with number & range.

Is it possible to include this feature in the gem, please?

**Comment by derrickreimer** [comment]
This gem always looks for the largest number in the column and increments from there, so it should automatically skip values that already exist. (Note that his means there is no guarantee that there wont be "gaps" in the numerical sequence.)
