### ISSUE TITLE
Using this as-is in Rails 5.2.1 doesnt work

### ISSUE THREAD

**Issue by bobbytables** [derrickreimer/sequenced#37]
Using a basic install of this doesn't seem to work with 5.2.1.

All of the sequential columns are set to 0 and aren't incremented on save. I also noticed it doesn't seem to do any queries at all to fetch the next ID in my logs.

**Comment by derrickreimer** [comment]
I'm afraid I don't have the bandwidth to diagnose this right now, but this implementation is pretty straightforward. Would you mind digging deeper on this?

**Comment by excid3** [comment]
I've updated the test suite to test against Rails 5.2+ and all the tests are passing.

Going to close this. If you can provide a test to reproduce the issue, please create a new issue and we'll get it fixed.
